/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KundeRouteImport } from './routes/kunde'
import { Route as PreislisteRouteImport } from './routes/preisliste'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBaustellenRouteImport } from './routes/admin.baustellen'
import { Route as AdminEinstellungenRouteImport } from './routes/admin.einstellungen'
import { Route as AdminKundenRouteImport } from './routes/admin.kunden'
import { Route as AdminLkwRouteImport } from './routes/admin.lkw'
import { Route as AdminMaterialRouteImport } from './routes/admin.material'
import { Route as AdminNeuerVorgangRouteImport } from './routes/admin.neuer-vorgang'
import { Route as AdminRechnungenRouteImport } from './routes/admin.rechnungen'
import { Route as AdminVorgaengeRouteImport } from './routes/admin.vorgaenge'
import { Route as KundeNeuerVorgangRouteImport } from './routes/kunde.neuer-vorgang'
import { Route as KundeRechnungenRouteImport } from './routes/kunde.rechnungen'
import { Route as KundeVorgaengeRouteImport } from './routes/kunde.vorgaenge'
import { Route as KundeNeuerVorgangIndexRouteImport } from './routes/kunde.neuer-vorgang.index'
import { Route as KundeNeuerVorgangDropoffRouteImport } from './routes/kunde.neuer-vorgang.dropoff'
import { Route as KundeNeuerVorgangPickupRouteImport } from './routes/kunde.neuer-vorgang.pickup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KundeRoute = KundeRouteImport.update({
  id: '/kunde',
  path: '/kunde',
  getParentRoute: () => rootRouteImport,
} as any)
const PreislisteRoute = PreislisteRouteImport.update({
  id: '/preisliste',
  path: '/preisliste',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBaustellenRoute = AdminBaustellenRouteImport.update({
  id: '/baustellen',
  path: '/baustellen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEinstellungenRoute = AdminEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKundenRoute = AdminKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLkwRoute = AdminLkwRouteImport.update({
  id: '/lkw',
  path: '/lkw',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialRoute = AdminMaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNeuerVorgangRoute = AdminNeuerVorgangRouteImport.update({
  id: '/neuer-vorgang',
  path: '/neuer-vorgang',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechnungenRoute = AdminRechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVorgaengeRoute = AdminVorgaengeRouteImport.update({
  id: '/vorgaenge',
  path: '/vorgaenge',
  getParentRoute: () => AdminRoute,
} as any)
const KundeNeuerVorgangRoute = KundeNeuerVorgangRouteImport.update({
  id: '/neuer-vorgang',
  path: '/neuer-vorgang',
  getParentRoute: () => KundeRoute,
} as any)
const KundeRechnungenRoute = KundeRechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => KundeRoute,
} as any)
const KundeVorgaengeRoute = KundeVorgaengeRouteImport.update({
  id: '/vorgaenge',
  path: '/vorgaenge',
  getParentRoute: () => KundeRoute,
} as any)
const KundeNeuerVorgangIndexRoute = KundeNeuerVorgangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundeNeuerVorgangRoute,
} as any)
const KundeNeuerVorgangDropoffRoute =
  KundeNeuerVorgangDropoffRouteImport.update({
    id: '/dropoff',
    path: '/dropoff',
    getParentRoute: () => KundeNeuerVorgangRoute,
  } as any)
const KundeNeuerVorgangPickupRoute = KundeNeuerVorgangPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => KundeNeuerVorgangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kunde': typeof KundeRouteWithChildren
  '/preisliste': typeof PreislisteRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin/baustellen': typeof AdminBaustellenRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/kunden': typeof AdminKundenRoute
  '/admin/lkw': typeof AdminLkwRoute
  '/admin/material': typeof AdminMaterialRoute
  '/admin/neuer-vorgang': typeof AdminNeuerVorgangRoute
  '/admin/rechnungen': typeof AdminRechnungenRoute
  '/admin/vorgaenge': typeof AdminVorgaengeRoute
  '/kunde/neuer-vorgang': typeof KundeNeuerVorgangRouteWithChildren
  '/kunde/rechnungen': typeof KundeRechnungenRoute
  '/kunde/vorgaenge': typeof KundeVorgaengeRoute
  '/admin/': typeof AdminIndexRoute
  '/kunde/neuer-vorgang/dropoff': typeof KundeNeuerVorgangDropoffRoute
  '/kunde/neuer-vorgang/pickup': typeof KundeNeuerVorgangPickupRoute
  '/kunde/neuer-vorgang/': typeof KundeNeuerVorgangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kunde': typeof KundeRouteWithChildren
  '/preisliste': typeof PreislisteRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin/baustellen': typeof AdminBaustellenRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/kunden': typeof AdminKundenRoute
  '/admin/lkw': typeof AdminLkwRoute
  '/admin/material': typeof AdminMaterialRoute
  '/admin/neuer-vorgang': typeof AdminNeuerVorgangRoute
  '/admin/rechnungen': typeof AdminRechnungenRoute
  '/admin/vorgaenge': typeof AdminVorgaengeRoute
  '/kunde/rechnungen': typeof KundeRechnungenRoute
  '/kunde/vorgaenge': typeof KundeVorgaengeRoute
  '/admin': typeof AdminIndexRoute
  '/kunde/neuer-vorgang/dropoff': typeof KundeNeuerVorgangDropoffRoute
  '/kunde/neuer-vorgang/pickup': typeof KundeNeuerVorgangPickupRoute
  '/kunde/neuer-vorgang': typeof KundeNeuerVorgangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kunde': typeof KundeRouteWithChildren
  '/preisliste': typeof PreislisteRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin/baustellen': typeof AdminBaustellenRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/kunden': typeof AdminKundenRoute
  '/admin/lkw': typeof AdminLkwRoute
  '/admin/material': typeof AdminMaterialRoute
  '/admin/neuer-vorgang': typeof AdminNeuerVorgangRoute
  '/admin/rechnungen': typeof AdminRechnungenRoute
  '/admin/vorgaenge': typeof AdminVorgaengeRoute
  '/kunde/neuer-vorgang': typeof KundeNeuerVorgangRouteWithChildren
  '/kunde/rechnungen': typeof KundeRechnungenRoute
  '/kunde/vorgaenge': typeof KundeVorgaengeRoute
  '/admin/': typeof AdminIndexRoute
  '/kunde/neuer-vorgang/dropoff': typeof KundeNeuerVorgangDropoffRoute
  '/kunde/neuer-vorgang/pickup': typeof KundeNeuerVorgangPickupRoute
  '/kunde/neuer-vorgang/': typeof KundeNeuerVorgangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kunde'
    | '/preisliste'
    | '/registrieren'
    | '/admin/baustellen'
    | '/admin/einstellungen'
    | '/admin/kunden'
    | '/admin/lkw'
    | '/admin/material'
    | '/admin/neuer-vorgang'
    | '/admin/rechnungen'
    | '/admin/vorgaenge'
    | '/kunde/neuer-vorgang'
    | '/kunde/rechnungen'
    | '/kunde/vorgaenge'
    | '/admin/'
    | '/kunde/neuer-vorgang/dropoff'
    | '/kunde/neuer-vorgang/pickup'
    | '/kunde/neuer-vorgang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kunde'
    | '/preisliste'
    | '/registrieren'
    | '/admin/baustellen'
    | '/admin/einstellungen'
    | '/admin/kunden'
    | '/admin/lkw'
    | '/admin/material'
    | '/admin/neuer-vorgang'
    | '/admin/rechnungen'
    | '/admin/vorgaenge'
    | '/kunde/rechnungen'
    | '/kunde/vorgaenge'
    | '/admin'
    | '/kunde/neuer-vorgang/dropoff'
    | '/kunde/neuer-vorgang/pickup'
    | '/kunde/neuer-vorgang'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kunde'
    | '/preisliste'
    | '/registrieren'
    | '/admin/baustellen'
    | '/admin/einstellungen'
    | '/admin/kunden'
    | '/admin/lkw'
    | '/admin/material'
    | '/admin/neuer-vorgang'
    | '/admin/rechnungen'
    | '/admin/vorgaenge'
    | '/kunde/neuer-vorgang'
    | '/kunde/rechnungen'
    | '/kunde/vorgaenge'
    | '/admin/'
    | '/kunde/neuer-vorgang/dropoff'
    | '/kunde/neuer-vorgang/pickup'
    | '/kunde/neuer-vorgang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KundeRoute: typeof KundeRouteWithChildren
  PreislisteRoute: typeof PreislisteRoute
  RegistrierenRoute: typeof RegistrierenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunde': {
      id: '/kunde'
      path: '/kunde'
      fullPath: '/kunde'
      preLoaderRoute: typeof KundeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preisliste': {
      id: '/preisliste'
      path: '/preisliste'
      fullPath: '/preisliste'
      preLoaderRoute: typeof PreislisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/baustellen': {
      id: '/admin/baustellen'
      path: '/baustellen'
      fullPath: '/admin/baustellen'
      preLoaderRoute: typeof AdminBaustellenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/einstellungen': {
      id: '/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AdminEinstellungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kunden': {
      id: '/admin/kunden'
      path: '/kunden'
      fullPath: '/admin/kunden'
      preLoaderRoute: typeof AdminKundenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lkw': {
      id: '/admin/lkw'
      path: '/lkw'
      fullPath: '/admin/lkw'
      preLoaderRoute: typeof AdminLkwRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/material': {
      id: '/admin/material'
      path: '/material'
      fullPath: '/admin/material'
      preLoaderRoute: typeof AdminMaterialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/neuer-vorgang': {
      id: '/admin/neuer-vorgang'
      path: '/neuer-vorgang'
      fullPath: '/admin/neuer-vorgang'
      preLoaderRoute: typeof AdminNeuerVorgangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rechnungen': {
      id: '/admin/rechnungen'
      path: '/rechnungen'
      fullPath: '/admin/rechnungen'
      preLoaderRoute: typeof AdminRechnungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vorgaenge': {
      id: '/admin/vorgaenge'
      path: '/vorgaenge'
      fullPath: '/admin/vorgaenge'
      preLoaderRoute: typeof AdminVorgaengeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kunde/neuer-vorgang': {
      id: '/kunde/neuer-vorgang'
      path: '/neuer-vorgang'
      fullPath: '/kunde/neuer-vorgang'
      preLoaderRoute: typeof KundeNeuerVorgangRouteImport
      parentRoute: typeof KundeRoute
    }
    '/kunde/rechnungen': {
      id: '/kunde/rechnungen'
      path: '/rechnungen'
      fullPath: '/kunde/rechnungen'
      preLoaderRoute: typeof KundeRechnungenRouteImport
      parentRoute: typeof KundeRoute
    }
    '/kunde/vorgaenge': {
      id: '/kunde/vorgaenge'
      path: '/vorgaenge'
      fullPath: '/kunde/vorgaenge'
      preLoaderRoute: typeof KundeVorgaengeRouteImport
      parentRoute: typeof KundeRoute
    }
    '/kunde/neuer-vorgang/': {
      id: '/kunde/neuer-vorgang/'
      path: '/'
      fullPath: '/kunde/neuer-vorgang/'
      preLoaderRoute: typeof KundeNeuerVorgangIndexRouteImport
      parentRoute: typeof KundeNeuerVorgangRoute
    }
    '/kunde/neuer-vorgang/dropoff': {
      id: '/kunde/neuer-vorgang/dropoff'
      path: '/dropoff'
      fullPath: '/kunde/neuer-vorgang/dropoff'
      preLoaderRoute: typeof KundeNeuerVorgangDropoffRouteImport
      parentRoute: typeof KundeNeuerVorgangRoute
    }
    '/kunde/neuer-vorgang/pickup': {
      id: '/kunde/neuer-vorgang/pickup'
      path: '/pickup'
      fullPath: '/kunde/neuer-vorgang/pickup'
      preLoaderRoute: typeof KundeNeuerVorgangPickupRouteImport
      parentRoute: typeof KundeNeuerVorgangRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBaustellenRoute: typeof AdminBaustellenRoute
  AdminEinstellungenRoute: typeof AdminEinstellungenRoute
  AdminKundenRoute: typeof AdminKundenRoute
  AdminLkwRoute: typeof AdminLkwRoute
  AdminMaterialRoute: typeof AdminMaterialRoute
  AdminNeuerVorgangRoute: typeof AdminNeuerVorgangRoute
  AdminRechnungenRoute: typeof AdminRechnungenRoute
  AdminVorgaengeRoute: typeof AdminVorgaengeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBaustellenRoute: AdminBaustellenRoute,
  AdminEinstellungenRoute: AdminEinstellungenRoute,
  AdminKundenRoute: AdminKundenRoute,
  AdminLkwRoute: AdminLkwRoute,
  AdminMaterialRoute: AdminMaterialRoute,
  AdminNeuerVorgangRoute: AdminNeuerVorgangRoute,
  AdminRechnungenRoute: AdminRechnungenRoute,
  AdminVorgaengeRoute: AdminVorgaengeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KundeNeuerVorgangRouteChildren {
  KundeNeuerVorgangDropoffRoute: typeof KundeNeuerVorgangDropoffRoute
  KundeNeuerVorgangPickupRoute: typeof KundeNeuerVorgangPickupRoute
  KundeNeuerVorgangIndexRoute: typeof KundeNeuerVorgangIndexRoute
}

const KundeNeuerVorgangRouteChildren: KundeNeuerVorgangRouteChildren = {
  KundeNeuerVorgangDropoffRoute: KundeNeuerVorgangDropoffRoute,
  KundeNeuerVorgangPickupRoute: KundeNeuerVorgangPickupRoute,
  KundeNeuerVorgangIndexRoute: KundeNeuerVorgangIndexRoute,
}

const KundeNeuerVorgangRouteWithChildren =
  KundeNeuerVorgangRoute._addFileChildren(KundeNeuerVorgangRouteChildren)

interface KundeRouteChildren {
  KundeNeuerVorgangRoute: typeof KundeNeuerVorgangRouteWithChildren
  KundeRechnungenRoute: typeof KundeRechnungenRoute
  KundeVorgaengeRoute: typeof KundeVorgaengeRoute
}

const KundeRouteChildren: KundeRouteChildren = {
  KundeNeuerVorgangRoute: KundeNeuerVorgangRouteWithChildren,
  KundeRechnungenRoute: KundeRechnungenRoute,
  KundeVorgaengeRoute: KundeVorgaengeRoute,
}

const KundeRouteWithChildren = KundeRoute._addFileChildren(KundeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KundeRoute: KundeRouteWithChildren,
  PreislisteRoute: PreislisteRoute,
  RegistrierenRoute: RegistrierenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
