/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WizardIndexRouteImport } from './routes/wizard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WizardPickupRouteImport } from './routes/wizard.pickup'
import { Route as WizardDropoffRouteImport } from './routes/wizard.dropoff'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardIndexRoute = WizardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WizardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WizardPickupRoute = WizardPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => WizardRoute,
} as any)
const WizardDropoffRoute = WizardDropoffRouteImport.update({
  id: '/dropoff',
  path: '/dropoff',
  getParentRoute: () => WizardRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/wizard': typeof WizardRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/wizard/dropoff': typeof WizardDropoffRoute
  '/wizard/pickup': typeof WizardPickupRoute
  '/admin/': typeof AdminIndexRoute
  '/wizard/': typeof WizardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/wizard/dropoff': typeof WizardDropoffRoute
  '/wizard/pickup': typeof WizardPickupRoute
  '/admin': typeof AdminIndexRoute
  '/wizard': typeof WizardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/wizard': typeof WizardRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/wizard/dropoff': typeof WizardDropoffRoute
  '/wizard/pickup': typeof WizardPickupRoute
  '/admin/': typeof AdminIndexRoute
  '/wizard/': typeof WizardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/wizard'
    | '/admin/companies'
    | '/admin/products'
    | '/admin/sites'
    | '/wizard/dropoff'
    | '/wizard/pickup'
    | '/admin/'
    | '/wizard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/admin/companies'
    | '/admin/products'
    | '/admin/sites'
    | '/wizard/dropoff'
    | '/wizard/pickup'
    | '/admin'
    | '/wizard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/history'
    | '/wizard'
    | '/admin/companies'
    | '/admin/products'
    | '/admin/sites'
    | '/wizard/dropoff'
    | '/wizard/pickup'
    | '/admin/'
    | '/wizard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  WizardRoute: typeof WizardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard/': {
      id: '/wizard/'
      path: '/'
      fullPath: '/wizard/'
      preLoaderRoute: typeof WizardIndexRouteImport
      parentRoute: typeof WizardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wizard/pickup': {
      id: '/wizard/pickup'
      path: '/pickup'
      fullPath: '/wizard/pickup'
      preLoaderRoute: typeof WizardPickupRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/dropoff': {
      id: '/wizard/dropoff'
      path: '/dropoff'
      fullPath: '/wizard/dropoff'
      preLoaderRoute: typeof WizardDropoffRouteImport
      parentRoute: typeof WizardRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WizardRouteChildren {
  WizardDropoffRoute: typeof WizardDropoffRoute
  WizardPickupRoute: typeof WizardPickupRoute
  WizardIndexRoute: typeof WizardIndexRoute
}

const WizardRouteChildren: WizardRouteChildren = {
  WizardDropoffRoute: WizardDropoffRoute,
  WizardPickupRoute: WizardPickupRoute,
  WizardIndexRoute: WizardIndexRoute,
}

const WizardRouteWithChildren =
  WizardRoute._addFileChildren(WizardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HistoryRoute: HistoryRoute,
  WizardRoute: WizardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
